# 工作流名称，将在 GitHub 的 Actions 页面显示
name: Deploy Blog

# 触发条件：当 push 到 main 分支时触发
on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  workflow_dispatch:    # 支持手动触发

# 工作流程
jobs:
  # 定义一个名为 deploy 的工作
  deploy:
    # 使用最新版的 Ubuntu 系统作为运行环境
    runs-on: ubuntu-latest
    steps:
      # 第一步：检出代码
      - uses: actions/checkout@v3  # 使用 checkout action 的 v3 版本
        with:
          # GitHub 会自动创建 GITHUB_TOKEN 密钥，用于认证
          token: ${{ secrets.GITHUB_TOKEN }}
          # 如果主题以子模块方式安装，需要设置 submodules: true
          submodules: true  # 如果你用了主题子模块

      # 第二步：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 指定 Node.js 版本

      # 第三步：设置 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest  # 使用最新版本的 pnpm

      # 第四步：安装依赖
      - name: Install Dependencies
        run: |
          echo "开始安装依赖..."
          pnpm install
          echo "依赖安装完成"

      # 第五步：设置 SSH 部署密钥
      - name: Setup Deploy Key
        env:
          # 从 GitHub Secrets 中获取部署密钥
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # 创建 ssh 目录
          mkdir -p ~/.ssh/
          # 写入密钥
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          # 设置密钥权限
          chmod 600 ~/.ssh/id_rsa
          # 添加 GitHub 到已知主机
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # 第六步：构建并检查
      - name: Build and Check
        run: |
          echo "开始清理..."
          pnpm run clean
          
          echo "开始构建..."
          pnpm run build
          
          echo "检查生成的文件..."
          ls -la public/
          echo "检查 index.html..."
          cat public/index.html | head -n 20
          
          echo "构建和检查完成"

      # 第七步：部署到云服务器
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "public/"
          target: "/opt/1panel/apps/openresty/openresty/www/blog"
          strip_components: 1

      # 检查服务器部署
      - name: Verify Server Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "检查服务器文件..."
            ls -la /opt/1panel/apps/openresty/openresty/www/blog/
            echo "检查 index.html..."
            cat /opt/1panel/apps/openresty/openresty/www/blog/index.html | head -n 20

      # 第八步：部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GIT_NAME: github-actions[bot]
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          echo "配置 Git..."
          git config --global user.name "$GIT_NAME"
          git config --global user.email "$GIT_EMAIL"
          
          echo "开始部署到 GitHub Pages..."
          pnpm run deploy
          
          echo "部署完成"

      # 完成通知
      - name: Deployment Status
        run: |
          echo "所有部署步骤已完成"
          date
